# Thông tin cơ bản của Server
cas.server.name=https://sso.nmt.io.vn
cas.server.prefix=${cas.server.name}/cas

# Tắt tài khoản mặc định (casuser::Mellon)
cas.authn.accept.users=

# ==========================================
# Cấu hình Kết nối Cơ sở dữ liệu (MySQL)
# ==========================================
cas.authn.jdbc.query[0].url=jdbc:mysql://127.0.0.1:3306/sql_sso?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
cas.authn.jdbc.query[0].user=sql_sso
cas.authn.jdbc.query[0].password=9ba8461edea27
cas.authn.jdbc.query[0].driverClass=com.mysql.cj.jdbc.Driver
cas.authn.jdbc.query[0].dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# Câu truy vấn xác thực (Vui lòng điều chỉnh theo bảng CSDL thực tế)
# Ví dụ dưới đây giả sử bạn dùng bảng 'users'
# ==========================================
cas.authn.jdbc.query[0].sql=SELECT password FROM users WHERE username=?
cas.authn.jdbc.query[0].fieldPassword=password
